name: LM_OraxenBridge
version: '${version}'
main: com.github.teraprath.lm_oraxenbridge.LM_OraxenBridge
api-version: '1.20'
authors:
  - TerryGHG
website: https://github.com/teraprath/LM_OraxenBridge
depend:
  - Oraxen
  - LevelledMobs
commands:
  lm_oraxenbridge:
    permission: lm.oraxenbridge.command